### ISSUE TITLE
这还是有漏洞

### ISSUE THREAD

**Issue by SnowUnderwater** [rHanbowChic/Notemon-View#1]
老兄这还是有漏洞

我记得这样似乎可以:`php://filter/read=convert.base64-encode/resource=../../../../../blog/wp-config.php`

**Comment by rHanbowChic** [comment]
Emm...这个是输入在哪里的？

**Comment by SnowUnderwater** [comment]
> Emm...这个是输入在哪里的？

你之前找的[那个地方](https://github.com/rHanbowChic/Notemon-View/blob/main/notemon-view.php#L41)
那样子不行的
我记得是能这么绕过

将输出base64解码就可获取内容

**Comment by rHanbowChic** [comment]
具体怎么样绕过呢？...

**Comment by SnowUnderwater** [comment]
草，代码似乎打错了，我对php伪协议可能有点误解）

> 具体怎么样绕过呢？...

php伪协议，data协议+base64 

URL?instance=xxx&record=[payload]

**Comment by rHanbowChic** [comment]
尝试复现漏洞，发现传给`is_file`的字符串是类似`../notemon__root/example_instance/records/data://text/plain;base64,Li4vbm90ZW1vbl9jdXJsLnB5`这样的。

`is_file`的值会是`False`,不会进一步读取文件，而会直接输出“不对...是你修改了URL参数吗？...”。

我尝试的是`&record=data://text/plain;base64,Li4vbm90ZW1vbl9jdXJsLnB5`，有其他触发漏洞的方式吗？

**Comment by SnowUnderwater** [comment]
> 尝试复现漏洞，发现传给`is_file`的字符串是类似`../notemon__root/example_instance/records/data://text/plain;base64,Li4vbm90ZW1vbl9jdXJsLnB5`这样的。
> 
> `is_file`的值会是`False`,不会进一步读取文件，而会直接输出“不对...是你修改了URL参数吗？...”。
> 
> 我尝试的是`&record=data://text/plain;base64,Li4vbm90ZW1vbl9jdXJsLnB5`，有其他触发漏洞的方式吗？

草
🤡
我是傻逼
没看清楚拼接字符串

当我什么也没说）

**Comment by rHanbowChic** [comment]
哦...至少让我去查了伪协议是什么。以后看来必须要注意....
说实话我对php是一点不懂（）
